# Generated by Django 6.0.6 on 2026-07-11 05:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("engagements", "0003_initial"),
        ("projects", "0001_initial"),
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="assigned_student",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="active_projects",
                to="users.studentprofile",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="sme",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects",
                to="users.smeprofile",
            ),
        ),
        migrations.AddField(
            model_name="projectmilestone",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="milestones",
                to="projects.project",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="engagement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviews",
                to="engagements.engagement",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="projects.project",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="reviewee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews_received",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="reviewer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews_given",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="savedstudent",
            name="sme",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="saved_students",
                to="users.smeprofile",
            ),
        ),
        migrations.AddField(
            model_name="savedstudent",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="saved_by",
                to="users.studentprofile",
            ),
        ),
        migrations.AddField(
            model_name="savedtask",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="saved_by",
                to="projects.project",
            ),
        ),
        migrations.AddField(
            model_name="savedtask",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="saved_tasks",
                to="users.studentprofile",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="review",
            unique_together={("project", "reviewer", "reviewee")},
        ),
        migrations.AlterUniqueTogether(
            name="savedstudent",
            unique_together={("sme", "student")},
        ),
        migrations.AlterUniqueTogether(
            name="savedtask",
            unique_together={("student", "project")},
        ),
    ]
