# Generated by Django 6.0.6 on 2026-07-09 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagements', '0003_initial'),
        ('projects', '0003_alter_review_unique_together_alter_review_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='engagement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='engagements.engagement'),
        ),
    ]
