# Generated by Django 6.0.6 on 2026-06-24 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("payments", "0001_initial"),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="project",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transaction",
                to="projects.project",
            ),
        ),
    ]
