# Generated by Django 6.0.6 on 2026-07-11 05:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("engagements", "0002_initial"),
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="engagement",
            name="sme",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="engagements",
                to="users.smeprofile",
            ),
        ),
        migrations.AddField(
            model_name="engagement",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="engagements",
                to="users.studentprofile",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="engagement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="engagements.engagement",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages_sent",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="attachment",
            name="message",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to="engagements.message",
            ),
        ),
    ]
