# Generated by Django 6.0.6 on 2026-07-11 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='resume',
            field=models.FileField(blank=True, upload_to='resumes/'),
        ),
    ]
